using Google.Apis.AndroidPublisher.v3.Data;
using System.Security.Cryptography;
using System.Text;

namespace DivisiBillWs;

internal static partial class PlayStore
{
    /// <summary>
    /// Verify the signature of a DivisiBill purchase. The signature is generated by the Play Store using the private key corresponding to the public key embedded in this method.
    /// </summary>
    /// <param name="signedData">The data to verify</param>
    /// <param name="signature">The signature used to verify the data</param>
    /// <returns>True if the signature is valid, false otherwise</returns>
    public static bool VerifyDivisiBillPurchaseSignature(string signedData, string signature)
    {
        const string divisiBillPublicKeyBase64 = @"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgfNwFZUg8fTc0Qd0PizHh+lZyjYJQDx2IH9XXZDE1X" +
        "/aTAp9s5offgtVYkaepHn17UAAHx8d4W6IVUSbtNlAiKxudmEo2tjoSYp6nnSlWRCs7Tzi6t91aMPmgaWUyx9/MCWFj3SRJz9cWhb84JiFDX3UecKKFUyOo+7NzeCvHOCvn" +
        "5JHe+kXMB+wxiYYKcy/vPsOuKlfxkf3GRvWsYJPRLxjB4hWm17HX+vT1AWXZxrLFI1iNiF0WFhYU72zunM7JAla6hUcHag/nFZYHfZxzjAf8YlFCMUbqPTZkINehRHDiM8lg" +
        "brHR5Df32rw+m3cLWKqd5wWqu4yr9+iOHdXzwIDAQAB";

        try
        {
            byte[] keyBytes = Convert.FromBase64String(divisiBillPublicKeyBase64);
            using var rsa = RSA.Create();
            rsa.ImportSubjectPublicKeyInfo(keyBytes, out _);

            byte[] dataBytes = Encoding.UTF8.GetBytes(signedData);
            byte[] signatureBytes = Convert.FromBase64String(signature);

            return rsa.VerifyData(dataBytes, signatureBytes, HashAlgorithmName.SHA1, RSASignaturePadding.Pkcs1);
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Check whether a purchase is recognized by the Play Store and is currently active.
    /// </summary>
    /// <param name="logger">An ILogger instance to use for logging</param>
    /// <param name="androidPurchase">The purchase object to validate</param>
    /// 
    /// <returns>True if the purchase is valid, false otherwise</returns>
    internal static bool VerifyPurchase(ILogger logger, AndroidPurchase? androidPurchase)
    {
        if (androidPurchase == null)
            LogVerifyPurchaseNullPurchase(logger);
        else if (string.IsNullOrEmpty(androidPurchase.PackageName))
            LogVerifyPurchaseMissingPropertyName(logger, nameof(AndroidPurchase.PackageName));
        else if (!androidPurchase.PackageName.Equals(LicenseStore.ExpectedPackageName)) // only DivisiBill Licenses can be used
            LogVerifyPurchaseInvalidPackageName(logger, androidPurchase.PackageName);
        else if (string.IsNullOrEmpty(androidPurchase.ProductId))
            LogVerifyPurchaseMissingPropertyName(logger, nameof(AndroidPurchase.ProductId));
        else if (string.IsNullOrEmpty(androidPurchase.PurchaseToken))
            LogVerifyPurchaseMissingPropertyName(logger, nameof(AndroidPurchase.PurchaseToken));
        else if (string.IsNullOrEmpty(androidPurchase.ObfuscatedAccountId))
            LogVerifyPurchaseMissingPropertyName(logger, nameof(AndroidPurchase.ObfuscatedAccountId));
        else
        {
            LogVerifyPurchaseAndroidPurchaseDetails(logger,
                androidPurchase.OrderId, androidPurchase.PackageName, androidPurchase.ProductId, androidPurchase.ObfuscatedAccountId, androidPurchase.PurchaseToken);
            string? verifiedOrderId = null;
            string? verifiedObfuscatedExternalAccountId = null;
            int? verifiedAcknowledgementState = null;
            string subscriptionState = string.Empty;
            bool isSubscription = androidPurchase.IsSubscription;

            // There is a test user that can be used to without calling the Play Store, which is useful for testing when the Internet is unavailable.
            // On an Android test system also see https://developer.android.com/google/play/billing/test#test-purchases for other options
            bool doNotCallPlayStore = Utility.IsDebug && androidPurchase.ObfuscatedAccountId is "VM2UM7jbkJVSv2XDovdyEQ392jjTtrRNSVDmB7AP0dfQdy004v";
            if (isSubscription)
            {
                try
                {
                    SubscriptionPurchaseV2? verifiedSubscriptionPurchase;
                    if (doNotCallPlayStore)
                    {
                        verifiedSubscriptionPurchase = new()
                        {
                            LatestOrderId = androidPurchase.OrderId,
                            AcknowledgementState = "ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED",
                            SubscriptionState = "SUBSCRIPTION_STATE_ACTIVE"
                        };
                        verifiedObfuscatedExternalAccountId = androidPurchase.ObfuscatedAccountId;
                    }
                    else
                    {
                        verifiedSubscriptionPurchase = LicenseCheck.GetSubscriptionPurchase(androidPurchase.PackageName, androidPurchase.PurchaseToken);
                        verifiedObfuscatedExternalAccountId = verifiedSubscriptionPurchase?.ExternalAccountIdentifiers.ObfuscatedExternalAccountId;
                    }
                    if (verifiedSubscriptionPurchase != null)
                    {
                        verifiedOrderId = verifiedSubscriptionPurchase.LatestOrderId;
                        verifiedAcknowledgementState = verifiedSubscriptionPurchase.AcknowledgementState.Equals("ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED") ? 1 : 0;
                        subscriptionState = verifiedSubscriptionPurchase.SubscriptionState;
                    }
                }
                catch (Exception ex)
                {
                    LogVerifyPurchaseSubscriptionException(logger, ex.Message);
                }
            }
            else
            {
                ProductPurchase? verifiedPurchase;
                try
                {
                    verifiedPurchase = doNotCallPlayStore
                        ? new()
                        {
                            OrderId = androidPurchase.OrderId,
                            AcknowledgementState = 1,
                            ObfuscatedExternalAccountId = androidPurchase.ObfuscatedAccountId
                        }
                        : LicenseCheck.GetProductPurchase(androidPurchase.PackageName, androidPurchase.ProductId, androidPurchase.PurchaseToken);
                    if (verifiedPurchase != null)
                    {
                        verifiedOrderId = verifiedPurchase.OrderId;
                        verifiedAcknowledgementState = verifiedPurchase.AcknowledgementState;
                        verifiedObfuscatedExternalAccountId = verifiedPurchase.ObfuscatedExternalAccountId;
                    }
                }
                catch (Exception ex)
                {
                    LogVerifyPurchasePurchaseException(logger, ex.Message);
                }
            }
            bool sameAccountId = string.Equals(verifiedObfuscatedExternalAccountId, androidPurchase.ObfuscatedAccountId);
            if (verifiedAcknowledgementState == null || verifiedOrderId == null || !sameAccountId)
                LogVerifyPurchaseVerificationFailed(logger);
            else
            {
                if (verifiedOrderId == null)
                    LogVerifyPurchaseOrderIdNull(logger);
                else if (doNotCallPlayStore)
                {
                    LogVerifyPurchaseTestOrder(logger);
                    return true;
                }
                else if (isSubscription)
                {
                    // Must be currently active
                    if (subscriptionState is "SUBSCRIPTION_STATE_ACTIVE" or "SUBSCRIPTION_STATE_IN_GRACE_PERIOD")
                    {
                        LogVerifyPurchaseSubscriptionSuccess(logger, verifiedAcknowledgementState == 1 ? "acknowledged" : "unacknowledged");
                        return true;
                    }
                    else
                    {
                        LogVerifyPurchaseSubscriptionStateFailed(logger, subscriptionState);
                        return false;
                    }
                }
                else
                {
                    LogVerifyPurchaseProductSuccess(logger, verifiedAcknowledgementState == 1 ? "acknowledged" : "unacknowledged");
                    return true;
                }
            }
        }
        return false;
    }

    [LoggerMessage(Level = LogLevel.Error, Message = "In VerifyPurchase, could not deserialize a purchase")]
    static partial void LogVerifyPurchaseNullPurchase(ILogger logger);

    [LoggerMessage(Level = LogLevel.Error, Message = "In VerifyPurchase, could not extract a {PropertyName}")]
    static partial void LogVerifyPurchaseMissingPropertyName(ILogger logger, string PropertyName);

    [LoggerMessage(Level = LogLevel.Error, Message = "In VerifyPurchase, package name was not com.autoplus.divisibill: {PackageName}")]
    static partial void LogVerifyPurchaseInvalidPackageName(ILogger logger, string PackageName);

    [LoggerMessage(Level = LogLevel.Information, Message = "In VerifyPurchase androidPurchase OrderId:{OrderId} PackageName:{PackageName} ProductId:{ProductId} ObfuscatedAccountId:{ObfuscatedAccountId} PurchaseToken:{PurchaseToken}")]
    static partial void LogVerifyPurchaseAndroidPurchaseDetails(ILogger logger, string? OrderId, string PackageName, string ProductId, string? ObfuscatedAccountId, string PurchaseToken);

    [LoggerMessage(Level = LogLevel.Error, Message = "In VerifyPurchase, exception calling Google to check subscription: {Message}")]
    static partial void LogVerifyPurchaseSubscriptionException(ILogger logger, string message);

    [LoggerMessage(Level = LogLevel.Error, Message = "In VerifyPurchase, exception calling Google to check purchase: {Message}")]
    static partial void LogVerifyPurchasePurchaseException(ILogger logger, string message);

    [LoggerMessage(Level = LogLevel.Error, Message = "In VerifyPurchase, could not verify purchase with Google")]
    static partial void LogVerifyPurchaseVerificationFailed(ILogger logger);

    [LoggerMessage(Level = LogLevel.Error, Message = "In VerifyPurchase, purchase.OrderId is null")]
    static partial void LogVerifyPurchaseOrderIdNull(ILogger logger);

    [LoggerMessage(Level = LogLevel.Information, Message = "In VerifyPurchase, test order, did not check play store")]
    static partial void LogVerifyPurchaseTestOrder(ILogger logger);

    [LoggerMessage(Level = LogLevel.Information, Message = "In VerifyPurchase, successfully verified {AcknowledgementState} license with Google")]
    static partial void LogVerifyPurchaseSubscriptionSuccess(ILogger logger, string acknowledgementState);

    [LoggerMessage(Level = LogLevel.Error, Message = "In VerifyPurchase, subscription verification failed because SubscriptionState = '{SubscriptionState}'")]
    static partial void LogVerifyPurchaseSubscriptionStateFailed(ILogger logger, string subscriptionState);

    [LoggerMessage(Level = LogLevel.Information, Message = "In VerifyPurchase, successfully verified {AcknowledgementState} license with Google")]
    static partial void LogVerifyPurchaseProductSuccess(ILogger logger, string acknowledgementState);
}
