using Google.Apis.AndroidPublisher.v3.Data;
using System.Security.Cryptography;
using System.Text;

namespace DivisiBillWs;

internal class PlayStore
{
    /// <summary>
    /// Verify the signature of a DivisiBill purchase. The signature is generated by the Play Store using the private key corresponding to the public key embedded in this method.
    /// </summary>
    /// <param name="signedData">The data to verify</param>
    /// <param name="signature">The signature used to verify the data</param>
    /// <returns>True if the signature is valid, false otherwise</returns>
    public static bool VerifyDivisiBillPurchaseSignature(string signedData, string signature)
    {
        const string divisiBillPublicKeyBase64 = @"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgfNwFZUg8fTc0Qd0PizHh+lZyjYJQDx2IH9XXZDE1X" +
        "/aTAp9s5offgtVYkaepHn17UAAHx8d4W6IVUSbtNlAiKxudmEo2tjoSYp6nnSlWRCs7Tzi6t91aMPmgaWUyx9/MCWFj3SRJz9cWhb84JiFDX3UecKKFUyOo+7NzeCvHOCvn" +
        "5JHe+kXMB+wxiYYKcy/vPsOuKlfxkf3GRvWsYJPRLxjB4hWm17HX+vT1AWXZxrLFI1iNiF0WFhYU72zunM7JAla6hUcHag/nFZYHfZxzjAf8YlFCMUbqPTZkINehRHDiM8lg" +
        "brHR5Df32rw+m3cLWKqd5wWqu4yr9+iOHdXzwIDAQAB";

        try
        {
            byte[] keyBytes = Convert.FromBase64String(divisiBillPublicKeyBase64);
            using var rsa = RSA.Create();
            rsa.ImportSubjectPublicKeyInfo(keyBytes, out _);

            byte[] dataBytes = Encoding.UTF8.GetBytes(signedData);
            byte[] signatureBytes = Convert.FromBase64String(signature);

            return rsa.VerifyData(dataBytes, signatureBytes, HashAlgorithmName.SHA1, RSASignaturePadding.Pkcs1);
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Check whether a purchase is recognized by the Play Store and is currently active.
    /// </summary>
    /// <param name="logger">An ILogger instance to use for logging</param>
    /// <param name="androidPurchase">The purchase object to validate</param>
    /// 
    /// <returns>True if the purchase is valid, false otherwise</returns>
    internal static bool VerifyPurchase(ILogger logger, AndroidPurchase? androidPurchase)
    {
        if (androidPurchase == null)
            logger.LogError("In VerifyPurchase, could not deserialize a purchase");
        else if (string.IsNullOrEmpty(androidPurchase.PackageName))
            logger.LogError("In VerifyPurchase, could not extract a {PropertyName}", nameof(AndroidPurchase.PackageName));
        else if (!androidPurchase.PackageName.Equals(LicenseStore.ExpectedPackageName)) // only DivisiBill Licenses can be used
            logger.LogError("In VerifyPurchase, package name was not com.autoplus.divisibill: {PackageName}", androidPurchase.PackageName);
        else if (string.IsNullOrEmpty(androidPurchase.ProductId))
            logger.LogError("In VerifyPurchase, could not extract a {PropertyName}", nameof(AndroidPurchase.ProductId));
        else if (string.IsNullOrEmpty(androidPurchase.PurchaseToken))
            logger.LogError("In VerifyPurchase, could not extract a {PropertyName}", nameof(AndroidPurchase.PurchaseToken));
        else
        {
            logger.LogInformation("In VerifyPurchase androidPurchase OrderId:{OrderId} PackageName:{PackageName} ProductId:{ProductId} ObfuscatedAccountId:{ObfuscatedAccountId} PurchaseToken:{PurchaseToken}",
                androidPurchase.OrderId, androidPurchase.PackageName, androidPurchase.ProductId, androidPurchase.ObfuscatedAccountId, androidPurchase.PurchaseToken);
            string? verifiedOrderId = null;
            string? verifiedObfuscatedExternalAccountId = null;
            int? verifiedAcknowledgementState = null;
            string subscriptionState = string.Empty;
            bool isSubscription = androidPurchase.IsSubscription;

            // There are a couple of reserved test order IDs that can be used to simulate purchases without calling the Play Store
            bool doNotCallPlayStore = Utility.IsDebug && androidPurchase.OrderId is "GPA.3334-3035-7547-40873" or "GPA.3332-0658-5128-80451";
            if (isSubscription)
            {
                SubscriptionPurchaseV2? verifiedSubscriptionPurchase = null;
                try
                {
                    if (doNotCallPlayStore)
                    {
                        verifiedSubscriptionPurchase = new()
                        {
                            LatestOrderId = androidPurchase.OrderId,
                            AcknowledgementState = "ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED",
                            SubscriptionState = "SUBSCRIPTION_STATE_ACTIVE"
                        };
                        verifiedObfuscatedExternalAccountId = androidPurchase.ObfuscatedAccountId;
                    }
                    else
                    {
                        verifiedSubscriptionPurchase = LicenseCheck.GetSubscriptionPurchase(androidPurchase.PackageName, androidPurchase.PurchaseToken);
                        verifiedObfuscatedExternalAccountId = verifiedSubscriptionPurchase?.ExternalAccountIdentifiers.ObfuscatedExternalAccountId;
                    }
                    if (verifiedSubscriptionPurchase != null)
                    {
                        verifiedOrderId = verifiedSubscriptionPurchase.LatestOrderId;
                        verifiedAcknowledgementState = verifiedSubscriptionPurchase.AcknowledgementState.Equals("ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED") ? 1 : 0;
                        subscriptionState = verifiedSubscriptionPurchase.SubscriptionState;
                    }
                }
                catch (Exception ex)
                {
                    logger.LogError("In VerifyPurchase, exception calling Google to check subscription: {Message}", ex.Message);
                }
            }
            else
            {
                ProductPurchase? verifiedPurchase = null;
                try
                {
                    verifiedPurchase = doNotCallPlayStore
                        ? new()
                        {
                            OrderId = androidPurchase.OrderId,
                            AcknowledgementState = 1,
                            ObfuscatedExternalAccountId = androidPurchase.ObfuscatedAccountId
                        }
                        : LicenseCheck.GetProductPurchase(androidPurchase.PackageName, androidPurchase.ProductId, androidPurchase.PurchaseToken);
                    if (verifiedPurchase != null)
                    {
                        verifiedOrderId = verifiedPurchase.OrderId;
                        verifiedAcknowledgementState = verifiedPurchase.AcknowledgementState;
                        verifiedObfuscatedExternalAccountId = verifiedPurchase.ObfuscatedExternalAccountId;
                    }
                }
                catch (Exception ex)
                {
                    logger.LogError("In VerifyPurchase, exception calling Google to check purchase: {Message}", ex.Message);
                }
            }
            bool sameAccountId = string.Equals(verifiedObfuscatedExternalAccountId, androidPurchase.ObfuscatedAccountId);
            if (verifiedAcknowledgementState == null || verifiedOrderId == null || !sameAccountId)
                logger.LogError("In VerifyPurchase, could not verify purchase with Google");
            else
            {
                if (verifiedOrderId == null)
                    logger.LogError("In VerifyPurchase, purchase.OrderId is null");
                else if (doNotCallPlayStore)
                {
                    logger.LogInformation("In VerifyPurchase, test order, did not check play store");
                    return true;
                }
                else if (isSubscription)
                {
                    // Must be currently active
                    if (subscriptionState is "SUBSCRIPTION_STATE_ACTIVE" or "SUBSCRIPTION_STATE_IN_GRACE_PERIOD")
                    {
                        logger.LogInformation("In VerifyPurchase, successfully verified {AcknowledgementState} license with Google", verifiedAcknowledgementState == 1 ? "acknowledged" : "unacknowledged");
                        return true;
                    }
                    else
                    {
                        logger.LogError("In VerifyPurchase, subscription verification failed because SubscriptionState = '{SubscriptionState}'", subscriptionState);
                        return false;
                    }
                }
                else
                {
                    logger.LogInformation("In VerifyPurchase, successfully verified {AcknowledgementState} license with Google", verifiedAcknowledgementState == 1 ? "acknowledged" : "unacknowledged");
                    return true;
                }
            }
        }
        return false;
    }
}
